name: qrophy
description: "Qrophy - AI Quiz Tournament App"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

  # Networking & API
  dio: ^5.7.0

  # File Handling
  file_picker: ^8.1.7

  # Sensors
  sensors_plus: ^6.1.1

  # Audio
  audioplayers: ^6.1.0

  # Animations
  confetti: ^0.8.0

  # UI Components
  go_router: ^14.8.1
  country_picker: ^2.0.27

  # Utilities
  uuid: ^4.5.1
  path: ^1.9.1
  intl: ^0.20.2
  collection: ^1.19.1
  equatable: ^2.0.7

  # Environment Variables
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - .env
